#!/bin/bash
echo "drwxr-xr-x 2 root root 4096 Nov 30 08:47 .                                                                                              

drwxr-xr-x 4 root root   78 Nov 30 03:22 ..                                                                                             

-rwxr--r-- 1 root root  114 Nov 30 06:08 0-current_working_directory                                                                    

-rw-r--r-- 1 root root   15 Nov 30 04:43 0-current_working_directory~                                                                   

-rw-r--r-- 1 root root    0 Nov 30 08:43 10-back                                                                                        

-rw-r--r-- 1 root root    0 Nov 30 08:43 11-lists                                                                                       

-rw-r--r-- 1 root root    0 Nov 30 08:43 12-file_type                                                                                   

-rw-r--r-- 1 root root    0 Nov 30 08:43 13-symbolic_link                                                                               

-rw-r--r-- 1 root root    0 Nov 30 08:43 14-copy_html                                                                                   

-rwxr--r-- 1 root root  116 Nov 30 07:20 1-listit                                                                                       

-rw-r--r-- 1 root root    0 Nov 30 06:18 1-listit~                                                                                      

-rwxr--r-- 1 root root   52 Nov 30 07:38 2-bring_me_home                                                                                

-rw-r--r-- 1 root root    0 Nov 30 07:24 2-bring_me_home~                                                                               

-rwxr--r-- 1 root root  521 Nov 30 08:36 3-listfiles                                                                                    

-rw-r--r-- 1 root root  520 Nov 30 08:34 3-listfiles~                                                                                   

-rw-r--r-- 1 root root    0 Nov 30 08:42 4-listmorefiles                                                                                

-rw-r--r-- 1 root root    0 Nov 30 08:42 5-listfilesdigitonly                                                                           

-rw-r--r-- 1 root root    0 Nov 30 08:42 6-firstdirectory                                                                               

-rw-r--r-- 1 root root    0 Nov 30 08:42 7-movethatfile                        
 -rw-r--r-- 1 root root    0 Nov 30 08:42 8-firstdelete                         
 -rw-r--r-- 1 root root    0 Nov 30 08:42 9-firstdirdeletion                     -rw-r--r-- 1 root root 1709 Nov 30 08:31 README.md                                                                                       -rw-r--r-- 1 root root   74 Nov 30 03:23 README.md~"